apiVersion: v2
appVersion: '1.0.5'
description: Qwen3.6 27B longest context — 77 t/s @ 262K (full native context, havenoammo Q3_K_XL + MTP)
name: llamacppqwen36mtpone
type: application
version: '1.0.5'
